import type { SubtitleCue } from '../types';

interface LanguageInfo {
  lang: string;
  name: string;
  isAutoGenerated: boolean;
}

export async function fetchAvailableLanguages(
  videoId: string
): Promise<LanguageInfo[]> {
  const res = await fetch(
    `/api/captions/languages?videoId=${encodeURIComponent(videoId)}`
  );
  if (!res.ok) throw new Error('Failed to fetch languages');
  const data = await res.json();
  return data.languages;
}

export async function fetchCaptions(
  videoId: string,
  lang: string
): Promise<SubtitleCue[]> {
  const res = await fetch(
    `/api/captions?videoId=${encodeURIComponent(videoId)}&lang=${encodeURIComponent(lang)}`
  );
  if (!res.ok) throw new Error('Failed to fetch captions');
  const data = await res.json();
  return data.cues;
}
