import { useEffect, useState } from 'react';
import type { VideoConfig, SubtitleCue, RecentMovie } from '../types';
import { fetchAvailableLanguages, fetchCaptions } from '../lib/captionApi';
import { parseSRT } from '../lib/srtParser';
import { getRecentMovies, saveRecentMovieSelection } from '../lib/storage';

interface Props {
  onStart: (config: VideoConfig) => void;
}

type Tab = 'youtube' | 'local';

interface LangOption {
  lang: string;
  name: string;
  isAutoGenerated: boolean;
}

export default function SetupForm({ onStart }: Props) {
  const [tab, setTab] = useState<Tab>('youtube');
  const [youtubeUrl, setYoutubeUrl] = useState('');
  const [languages, setLanguages] = useState<LangOption[]>([]);
  const [sourceLang, setSourceLang] = useState('');
  const [targetLang, setTargetLang] = useState('');
  const [recentMovies, setRecentMovies] = useState<RecentMovie[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  // Local file state
  const [localVideoFile, setLocalVideoFile] = useState<File | null>(null);
  const [sourceSrtFile, setSourceSrtFile] = useState<File | null>(null);
  const [targetSrtFile, setTargetSrtFile] = useState<File | null>(null);

  function getDefaultLangs(langs: LangOption[]) {
    // Prefer Italian for learning and English for translations when available.
    const italian = langs.find((l) => l.lang.startsWith('it'));
    const english = langs.find((l) => l.lang.startsWith('en'));

    const preferredSource = italian?.lang || langs[0]?.lang || '';
    const preferredTarget =
      english?.lang || langs.find((l) => l.lang !== preferredSource)?.lang || preferredSource;

    return { source: preferredSource, target: preferredTarget };
  }

  useEffect(() => {
    void loadRecentMovies();
  }, []);

  async function loadRecentMovies() {
    try {
      setRecentMovies(await getRecentMovies(8));
    } catch {
      setRecentMovies([]);
    }
  }

  async function fetchLanguagesForVideo(
    rawUrl: string,
    preferred?: { source: string; target: string }
  ) {
    const videoUrl = rawUrl.trim();
    if (!videoUrl) return;

    setLoading(true);
    setError('');
    try {
      const langs = await fetchAvailableLanguages(videoUrl);
      setLanguages(langs);
      if (langs.length) {
        const defaults = getDefaultLangs(langs);
        const source =
          preferred?.source && langs.some((l) => l.lang === preferred.source)
            ? preferred.source
            : defaults.source;
        const target =
          preferred?.target && langs.some((l) => l.lang === preferred.target)
            ? preferred.target
            : defaults.target;
        setSourceLang(source);
        setTargetLang(target);
      }
    } catch {
      setError('Could not fetch languages. Check the URL and try again.');
    } finally {
      setLoading(false);
    }
  }

  async function handleFetchLanguages() {
    await fetchLanguagesForVideo(youtubeUrl);
  }

  function handleUseRecentYouTube(movie: RecentMovie) {
    setYoutubeUrl(movie.videoUrl);
    void fetchLanguagesForVideo(movie.videoUrl, {
      source: movie.sourceLang,
      target: movie.targetLang,
    });
  }

  async function handleStartYouTube() {
    if (!sourceLang || !targetLang) return;
    setLoading(true);
    setError('');
    try {
      const [sourceCues, targetCues] = await Promise.all([
        fetchCaptions(youtubeUrl, sourceLang),
        fetchCaptions(youtubeUrl, targetLang),
      ]);
      onStart({
        source: 'youtube',
        videoUrl: youtubeUrl,
        sourceLangCues: sourceCues,
        targetLangCues: targetCues,
        sourceLang,
        targetLang,
      });
      void saveRecentMovieSelection({
        source: 'youtube',
        videoUrl: youtubeUrl,
        sourceLang,
        targetLang,
      }).then(() => loadRecentMovies());
    } catch {
      setError('Failed to fetch captions.');
    } finally {
      setLoading(false);
    }
  }

  async function handleStartLocal() {
    if (!localVideoFile || !sourceSrtFile || !targetSrtFile) return;
    setLoading(true);
    setError('');
    try {
      const [sourceText, targetText] = await Promise.all([
        sourceSrtFile.text(),
        targetSrtFile.text(),
      ]);
      const sourceCues: SubtitleCue[] = parseSRT(sourceText);
      const targetCues: SubtitleCue[] = parseSRT(targetText);
      const videoUrl = URL.createObjectURL(localVideoFile);
      onStart({
        source: 'local',
        videoUrl,
        sourceLangCues: sourceCues,
        targetLangCues: targetCues,
        sourceLang: 'source',
        targetLang: 'target',
      });
      void saveRecentMovieSelection(
        {
          source: 'local',
          videoUrl: localVideoFile.name,
          sourceLang: 'source',
          targetLang: 'target',
        },
        localVideoFile.name
      ).then(() => loadRecentMovies());
    } catch {
      setError('Failed to parse subtitle files.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="max-w-lg mx-auto mt-12 p-6 bg-gray-900 rounded-xl shadow-lg">
      <h1 className="text-2xl font-bold text-white mb-6 text-center">
        LangVid
      </h1>

      {/* Tab buttons */}
      <div className="flex mb-6 border-b border-gray-700">
        <button
          className={`flex-1 py-2 text-center font-medium ${
            tab === 'youtube'
              ? 'text-blue-400 border-b-2 border-blue-400'
              : 'text-gray-400 hover:text-gray-200'
          }`}
          onClick={() => setTab('youtube')}
        >
          YouTube
        </button>
        <button
          className={`flex-1 py-2 text-center font-medium ${
            tab === 'local'
              ? 'text-blue-400 border-b-2 border-blue-400'
              : 'text-gray-400 hover:text-gray-200'
          }`}
          onClick={() => setTab('local')}
        >
          Local File
        </button>
      </div>

      {error && (
        <div className="mb-4 p-3 bg-red-900/50 border border-red-700 rounded text-red-300 text-sm">
          {error}
        </div>
      )}

      {tab === 'youtube' ? (
        <div className="space-y-4">
          {recentMovies.some((m) => m.source === 'youtube') && (
            <div>
              <p className="text-sm text-gray-300 mb-2">Recent movies</p>
              <div className="flex flex-wrap gap-2">
                {recentMovies
                  .filter((m) => m.source === 'youtube')
                  .slice(0, 5)
                  .map((movie) => (
                    <button
                      key={movie.id}
                      onClick={() => handleUseRecentYouTube(movie)}
                      className="text-xs px-2 py-1 rounded bg-gray-800 text-gray-200 hover:bg-gray-700"
                      title={movie.videoUrl}
                    >
                      {movie.label || movie.videoUrl}
                    </button>
                  ))}
              </div>
            </div>
          )}

          <div>
            <label className="block text-sm text-gray-300 mb-1">
              YouTube URL
            </label>
            <div className="flex gap-2">
              <input
                type="text"
                value={youtubeUrl}
                onChange={(e) => setYoutubeUrl(e.target.value)}
                placeholder="https://www.youtube.com/watch?v=..."
                className="flex-1 px-3 py-2 bg-gray-800 border border-gray-700 rounded text-white placeholder-gray-500 text-sm"
              />
              <button
                onClick={handleFetchLanguages}
                disabled={loading || !youtubeUrl.trim()}
                className="px-4 py-2 bg-blue-600 text-white rounded text-sm font-medium hover:bg-blue-500 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {loading ? '...' : 'Fetch'}
              </button>
            </div>
          </div>

          {languages.length > 0 && (
            <>
              <div>
                <label className="block text-sm text-gray-300 mb-1">
                  Learning Language (subtitles you want to learn)
                </label>
                <select
                  value={sourceLang}
                  onChange={(e) => setSourceLang(e.target.value)}
                  className="w-full px-3 py-2 bg-gray-800 border border-gray-700 rounded text-white text-sm"
                >
                  {languages.map((l) => (
                    <option key={l.lang} value={l.lang}>
                      {l.name}
                      {l.isAutoGenerated ? ' (auto)' : ''}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm text-gray-300 mb-1">
                  Your Language (translations)
                </label>
                <select
                  value={targetLang}
                  onChange={(e) => setTargetLang(e.target.value)}
                  className="w-full px-3 py-2 bg-gray-800 border border-gray-700 rounded text-white text-sm"
                >
                  {languages.map((l) => (
                    <option key={l.lang} value={l.lang}>
                      {l.name}
                      {l.isAutoGenerated ? ' (auto)' : ''}
                    </option>
                  ))}
                </select>
              </div>
              <button
                onClick={handleStartYouTube}
                disabled={loading || !sourceLang || !targetLang}
                className="w-full py-3 bg-green-600 text-white rounded-lg font-medium hover:bg-green-500 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {loading ? 'Loading captions...' : 'Start Watching'}
              </button>
            </>
          )}
        </div>
      ) : (
        <div className="space-y-4">
          {recentMovies.some((m) => m.source === 'local') && (
            <div className="rounded-lg border border-gray-800 p-3">
              <p className="text-sm text-gray-300 mb-2">Recent local selections</p>
              <div className="space-y-1">
                {recentMovies
                  .filter((m) => m.source === 'local')
                  .slice(0, 3)
                  .map((movie) => (
                    <p key={movie.id} className="text-xs text-gray-400">
                      {movie.label || movie.videoUrl}
                    </p>
                  ))}
              </div>
            </div>
          )}

          <div>
            <label className="block text-sm text-gray-300 mb-1">
              Video File
            </label>
            <input
              type="file"
              accept="video/*"
              onChange={(e) => setLocalVideoFile(e.target.files?.[0] || null)}
              className="w-full text-sm text-gray-400 file:mr-4 file:py-2 file:px-4 file:rounded file:border-0 file:bg-gray-700 file:text-white file:cursor-pointer"
            />
          </div>
          <div>
            <label className="block text-sm text-gray-300 mb-1">
              Learning Language Subtitles (.srt)
            </label>
            <input
              type="file"
              accept=".srt"
              onChange={(e) => setSourceSrtFile(e.target.files?.[0] || null)}
              className="w-full text-sm text-gray-400 file:mr-4 file:py-2 file:px-4 file:rounded file:border-0 file:bg-gray-700 file:text-white file:cursor-pointer"
            />
          </div>
          <div>
            <label className="block text-sm text-gray-300 mb-1">
              Your Language Subtitles (.srt)
            </label>
            <input
              type="file"
              accept=".srt"
              onChange={(e) => setTargetSrtFile(e.target.files?.[0] || null)}
              className="w-full text-sm text-gray-400 file:mr-4 file:py-2 file:px-4 file:rounded file:border-0 file:bg-gray-700 file:text-white file:cursor-pointer"
            />
          </div>
          <button
            onClick={handleStartLocal}
            disabled={
              loading || !localVideoFile || !sourceSrtFile || !targetSrtFile
            }
            className="w-full py-3 bg-green-600 text-white rounded-lg font-medium hover:bg-green-500 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? 'Loading...' : 'Start Watching'}
          </button>
        </div>
      )}
    </div>
  );
}
